// Shape validation for the user-authored route and middleware modules.
//
// Route handler module — `export const handlers = ...` — accepts:
//   * a single function: `(ctx) => Response`
//   * a method dispatch object: `{ GET(ctx) {}, POST(ctx) {} }`
//
// Middleware module — `export default ...` — accepts a single function:
//   `(ctx) => ctx.next()`
//
// Both validators are invoked from the per-route virtual module generated by
// `src/build/nitro-config.ts`, so shape errors surface at import time.

import type {
  Handler,
  HttpMethod,
  LayoutComponent,
  MethodHandlers,
  Middleware,
  PageComponent,
  RequestHandler,
} from "./types.ts";

export type {
  Handler,
  HandlerContext,
  HandlerResult,
  HandlerReturn,
  HttpMethod,
  LayoutComponent,
  LayoutProps,
  MethodHandlers,
  Middleware,
  PageComponent,
  PageProps,
  RequestHandler,
} from "./types.ts";

/** Alias kept for callers that referenced the pre-refactor name. */
export type RouteHandler = Handler;

const HTTP_METHODS = new Set<HttpMethod>([
  "GET",
  "HEAD",
  "POST",
  "PUT",
  "DELETE",
  "PATCH",
  "OPTIONS",
]);

/**
 * Returns the validated `handlers` export from a route module, or `null` when
 * the module has no `handlers` (in which case the framework falls back to an
 * auto-GET that renders the page with `data: undefined`).
 */
export function validateHandler(mod: unknown): RouteHandler | null {
  if (!mod || typeof mod !== "object") return null;
  const handlers = (mod as { handlers?: unknown }).handlers;
  if (handlers === undefined) return null;
  if (typeof handlers === "function") {
    return handlers as RequestHandler;
  }
  if (handlers && typeof handlers === "object") {
    const out: MethodHandlers = {};
    for (const [key, value] of Object.entries(handlers)) {
      if (!(HTTP_METHODS as Set<string>).has(key)) {
        throw new TypeError(
          `handler exports unknown HTTP method "${key}" (expected one of: ${[...HTTP_METHODS].join(
            ", ",
          )})`,
        );
      }
      if (typeof value !== "function") {
        throw new TypeError(`handler for method "${key}" must be a function, got ${typeof value}`);
      }
      out[key as HttpMethod] = value as RequestHandler;
    }
    return out;
  }
  throw new TypeError("`handlers` export must be a function or a method-map object");
}

/**
 * Returns the route's `default` export (the page component) if present, or
 * `null` when the module has no default export.
 */
export function validatePage(mod: unknown): PageComponent | null {
  if (!mod || typeof mod !== "object") return null;
  const def = (mod as { default?: unknown }).default;
  if (def == null) return null;
  if (typeof def !== "function") {
    throw new TypeError(
      `route's default export must be a page component (function), got ${typeof def}`,
    );
  }
  return def as PageComponent;
}

/**
 * Returns a layout module's `default` export. A `_layout.tsx` must export a
 * default function — empty / missing default exports throw at load time so
 * they show up immediately rather than silently rendering an unwrapped page.
 */
export function validateLayout(mod: unknown): LayoutComponent {
  if (!mod || typeof mod !== "object") {
    throw new TypeError("_layout module must be an object");
  }
  const def = (mod as { default?: unknown }).default;
  if (typeof def !== "function") {
    throw new TypeError(`_layout module must \`export default\` a function, got ${typeof def}`);
  }
  return def as LayoutComponent;
}

export function validateMiddleware(mod: unknown): Middleware {
  if (!mod || typeof mod !== "object") {
    throw new TypeError("middleware module must be an object");
  }
  const def = (mod as { default?: unknown }).default;
  if (typeof def !== "function") {
    throw new TypeError(`middleware module must \`export default\` a function, got ${typeof def}`);
  }
  return def as Middleware;
}
